"""Initial schema: calls, webhook events and appointments.

This is the baseline migration; `alembic upgrade head` on an empty database creates every table
the application needs. Later schema changes are added as new files in this directory.

Revision ID: 0001
Revises:
Create Date: 2026-09-28 07:43:20.723189

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.database  # Custom column types (UTCDateTime) referenced below.

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("external_call_id", sa.String(length=128), nullable=True),
        sa.Column("agent_id", sa.String(length=100), nullable=False),
        sa.Column("from_number", sa.String(length=32), nullable=True),
        sa.Column("to_number", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=True),
        sa.Column("started_at", app.core.database.UTCDateTime(), nullable=True),
        sa.Column("ended_at", app.core.database.UTCDateTime(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("sentiment", sa.String(length=32), nullable=True),
        sa.Column("analysis", sa.JSON(), nullable=True),
        sa.Column("created_at", app.core.database.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.core.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calls")),
        sa.UniqueConstraint("external_call_id", name=op.f("uq_calls_external_call_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_calls_idempotency_key")),
    )
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_calls_agent_id"), ["agent_id"], unique=False)
        batch_op.create_index("ix_calls_created_at_id", ["created_at", "id"], unique=False)
        batch_op.create_index(batch_op.f("ix_calls_status"), ["status"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("call_external_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("received_at", app.core.database.UTCDateTime(), nullable=False),
        sa.Column("processed_at", app.core.database.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_events_event_id")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_events_call_external_id"), ["call_external_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_events_status"), ["status"], unique=False)

    op.create_table(
        "appointments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("customer_name", sa.String(length=100), nullable=False),
        sa.Column("customer_phone", sa.String(length=32), nullable=False),
        sa.Column("start_time", app.core.database.UTCDateTime(), nullable=False),
        sa.Column("end_time", app.core.database.UTCDateTime(), nullable=False),
        sa.Column("call_id", sa.String(length=36), nullable=True),
        sa.Column("calendar_event_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", app.core.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_appointments_call_id_calls")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_appointments_call_id"), ["call_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_appointments_start_time"), ["start_time"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointments_start_time"))
        batch_op.drop_index(batch_op.f("ix_appointments_call_id"))

    op.drop_table("appointments")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_status"))
        batch_op.drop_index(batch_op.f("ix_events_call_external_id"))

    op.drop_table("events")
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calls_status"))
        batch_op.drop_index("ix_calls_created_at_id")
        batch_op.drop_index(batch_op.f("ix_calls_agent_id"))

    op.drop_table("calls")
    # ### end Alembic commands ###
